import Head from 'next/head'
const PageHead = () =>{
    return(
       <Head>
        <title>Developer DAO FM 🎧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Frame 2.png" sizes="16x16" />
      </Head>
    )
}
export default PageHead

